import { createSlice, createAsyncThunk } from '@reduxjs/toolkit';
import { axiosReq } from "../../axios";


export const fetchPosts = createAsyncThunk("post/fetchPosts",
    () => {
        const response = axiosReq.get(`/?areaCode=IN&isBrazil=false&categoryId=1`);
        return response;
    });

export const storeSlice = createSlice({
    name: 'store',
    initialState: {
        games: [
            {
                "gameIdentity": {
                    "gameInfoId": 18366,
                    "gameName": "TADA70:148",
                    "gameUrl": "bingo-carnaval-by-tada",
                    "gameChannel": "0",
                    "socketNameSpace": "bingo-carnaval-by-tada"
                },
                "fullName": "Bingo Carnaval",
                "thumbnail": "https://bc.imgix.net/game/image/7d7037ca59.png",
                "providerName": "TaDa",
                "rtpDes": 97.00000000,
                "iconThreeFour": "https://bc.imgix.net/game/image/b2e5bc66f5.png",
                "betco34": "https://bc.imgix.net/game/image/common.png",
                "online": 3,
                "providerIcon": "https://bc.imgix.net/game/image/aa905d6c31.png",
                "providerIconWhite": "https://bc.imgix.net/game/image/3ad4290103.png",
                "isRestricted": 0,
                "categoryName": "Slots",
                "rateScore": 4,
                "rateNum": 1,
                "retrieveId": "hot",
                "onlineUsers": 1,
                "tags": [
                    "Buy extra ball feature",
                    "Bingo"
                ],
                "corner": null,
                "wagerPercentAge": 50.00000000,
                "translatedTags": {},
                "disabled": false
            },
            {
                "gameIdentity": {
                    "gameInfoId": 1969,
                    "gameName": "softswiss:belatra:BingoSoccer",
                    "gameUrl": "bingo-soccer-by-belatra",
                    "gameChannel": "0",
                    "socketNameSpace": "bingo-soccer-by-belatra"
                },
                "fullName": "Bingo Soccer",
                "thumbnail": "https://bc.imgix.net/game/image/5a2c8048-b4c3-4de5-87fd-b50224abf0ae.png",
                "providerName": "Belatra",
                "rtpDes": 99.00000000,
                "iconThreeFour": "https://bc.imgix.net/game/image/6c55a75b6c.png",
                "betco34": "https://bc.imgix.net/game/image/common.png",
                "online": 3,
                "providerIcon": "https://bc.imgix.net/game/image/6bf141b73a.png",
                "providerIconWhite": "https://bc.imgix.net/game/image/c389a6afda.png",
                "isRestricted": 0,
                "categoryName": "Slots",
                "rateScore": 4,
                "rateNum": 1,
                "retrieveId": "hot",
                "onlineUsers": 1,
                "tags": [
                    "Buy extra ball feature",
                    "Bingo",
                    "Sports",
                    "Belatra"
                ],
                "corner": null,
                "wagerPercentAge": null,
                "translatedTags": {},
                "disabled": false
            },
            {
                "gameIdentity": {
                    "gameInfoId": 18082,
                    "gameName": "PPS32:wildbingo",
                    "gameUrl": "wild-bingo-by-platipus",
                    "gameChannel": "0",
                    "socketNameSpace": "wild-bingo-by-platipus"
                },
                "fullName": "Wild Bingo",
                "thumbnail": "https://bc.imgix.net/game/image/e119459b40.png",
                "providerName": "Platipus",
                "rtpDes": 96.00000000,
                "iconThreeFour": "https://bc.imgix.net/game/image/1b1468b2b2.png",
                "betco34": "https://bc.imgix.net/game/image/common.png",
                "online": 3,
                "providerIcon": "https://bc.imgix.net/game/image/9aec8f2b38.png",
                "providerIconWhite": "https://bc.imgix.net/game/image/9419418148.png",
                "isRestricted": 0,
                "categoryName": "Slots",
                "rateScore": 4,
                "rateNum": 1,
                "retrieveId": "hot",
                "onlineUsers": 1,
                "tags": [
                    "Buy extra ball feature",
                    "Bingo jackpot",
                    "Bingo"
                ],
                "corner": null,
                "wagerPercentAge": 100.00000000,
                "translatedTags": {},
                "disabled": false
            },
            {
                "gameIdentity": {
                    "gameInfoId": 18365,
                    "gameName": "TADA70:139",
                    "gameUrl": "fortune-bingo-by-tada",
                    "gameChannel": "0",
                    "socketNameSpace": "fortune-bingo-by-tada"
                },
                "fullName": "Fortune Bingo",
                "thumbnail": "https://bc.imgix.net/game/image/138c92d17c.png",
                "providerName": "TaDa",
                "rtpDes": 97.00000000,
                "iconThreeFour": "https://bc.imgix.net/game/image/8a8c658a41.png",
                "betco34": "https://bc.imgix.net/game/image/common.png",
                "online": 3,
                "providerIcon": "https://bc.imgix.net/game/image/aa905d6c31.png",
                "providerIconWhite": "https://bc.imgix.net/game/image/3ad4290103.png",
                "isRestricted": 0,
                "categoryName": "Slots",
                "rateScore": 4,
                "rateNum": 1,
                "retrieveId": "hot",
                "onlineUsers": 1,
                "tags": [
                    "Buy extra ball feature",
                    "Bingo"
                ],
                "corner": null,
                "wagerPercentAge": 50.00000000,
                "translatedTags": {},
                "disabled": false
            },
            {
                "gameIdentity": {
                    "gameInfoId": 18367,
                    "gameName": "TADA70:151",
                    "gameUrl": "super-bingo-by-tada",
                    "gameChannel": "0",
                    "socketNameSpace": "super-bingo-by-tada"
                },
                "fullName": "Super Bingo",
                "thumbnail": "https://bc.imgix.net/game/image/642e9d9960.png",
                "providerName": "TaDa",
                "rtpDes": 97.00000000,
                "iconThreeFour": "https://bc.imgix.net/game/image/fb61080b94.png",
                "betco34": "https://bc.imgix.net/game/image/common.png",
                "online": 3,
                "providerIcon": "https://bc.imgix.net/game/image/aa905d6c31.png",
                "providerIconWhite": "https://bc.imgix.net/game/image/3ad4290103.png",
                "isRestricted": 0,
                "categoryName": "Slots",
                "rateScore": 4,
                "rateNum": 1,
                "retrieveId": "hot",
                "onlineUsers": 1,
                "tags": [
                    "Buy extra ball feature",
                    "Bingo"
                ],
                "corner": null,
                "wagerPercentAge": 50.00000000,
                "translatedTags": {},
                "disabled": false
            },
            {
                "gameIdentity": {
                    "gameInfoId": 18370,
                    "gameName": "TADA70:143",
                    "gameUrl": "bonus-bingo-by-tada",
                    "gameChannel": "0",
                    "socketNameSpace": "bonus-bingo-by-tada"
                },
                "fullName": "Bonus Bingo",
                "thumbnail": "https://bc.imgix.net/game/image/1b82ad95d2.png",
                "providerName": "TaDa",
                "rtpDes": 97.00000000,
                "iconThreeFour": "https://bc.imgix.net/game/image/a5987799c8.png",
                "betco34": "https://bc.imgix.net/game/image/common.png",
                "online": 3,
                "providerIcon": "https://bc.imgix.net/game/image/aa905d6c31.png",
                "providerIconWhite": "https://bc.imgix.net/game/image/3ad4290103.png",
                "isRestricted": 0,
                "categoryName": "Slots",
                "rateScore": 4,
                "rateNum": 1,
                "retrieveId": "hot",
                "onlineUsers": 1,
                "tags": [
                    "Buy extra ball feature",
                    "Bingo"
                ],
                "corner": null,
                "wagerPercentAge": 50.00000000,
                "translatedTags": {},
                "disabled": false
            },
            {
                "gameIdentity": {
                    "gameInfoId": 18364,
                    "gameName": "TADA70:150",
                    "gameUrl": "lucky-bingo-by-tada",
                    "gameChannel": "0",
                    "socketNameSpace": "lucky-bingo-by-tada"
                },
                "fullName": "Lucky Bingo",
                "thumbnail": "https://bc.imgix.net/game/image/2541ecf464.png",
                "providerName": "TaDa",
                "rtpDes": 97.00000000,
                "iconThreeFour": "https://bc.imgix.net/game/image/2d1a431b6b.png",
                "betco34": "https://bc.imgix.net/game/image/common.png",
                "online": 3,
                "providerIcon": "https://bc.imgix.net/game/image/aa905d6c31.png",
                "providerIconWhite": "https://bc.imgix.net/game/image/3ad4290103.png",
                "isRestricted": 0,
                "categoryName": "Slots",
                "rateScore": 4,
                "rateNum": 1,
                "retrieveId": "hot",
                "onlineUsers": 1,
                "tags": [
                    "Buy extra ball feature",
                    "Bingo"
                ],
                "corner": null,
                "wagerPercentAge": 50.00000000,
                "translatedTags": {},
                "disabled": false
            },
            {
                "gameIdentity": {
                    "gameInfoId": 9601,
                    "gameName": "sgt16:a3ed9c496f3b496fedd7e911418546875ab64472",
                    "gameUrl": "extra-bingo-mobile-by-wazdan",
                    "gameChannel": "0",
                    "socketNameSpace": "extra-bingo-mobile-by-wazdan"
                },
                "fullName": "Extra Bingo Mobile",
                "thumbnail": "https://bc.imgix.net/game/image/7be5c557-7757-4c3e-b84f-eefec3b33a23.png",
                "providerName": "Wazdan",
                "rtpDes": 95.96000000,
                "iconThreeFour": "https://bc.imgix.net/game/image/common.png",
                "betco34": "https://bc.imgix.net/game/image/common.png",
                "online": 3,
                "providerIcon": "https://bc.imgix.net/game/image/826ecb0385.png",
                "providerIconWhite": "https://bc.imgix.net/game/image/faf99c6a4b.png",
                "isRestricted": 0,
                "categoryName": "Slots",
                "rateScore": 4,
                "rateNum": 1,
                "retrieveId": "hot",
                "onlineUsers": 1,
                "tags": [
                    "Buy extra ball feature",
                    "Gamble feature",
                    "High volatility",
                    "Bingo"
                ],
                "corner": null,
                "wagerPercentAge": 50.00000000,
                "translatedTags": {},
                "disabled": false
            },
            {
                "gameIdentity": {
                    "gameInfoId": 13793,
                    "gameName": "mg18:SMG_amazingPharaoh",
                    "gameUrl": "amazing-pharaoh-by-neko-games",
                    "gameChannel": "0",
                    "socketNameSpace": "amazing-pharaoh-by-neko-games"
                },
                "fullName": "Amazing Pharaoh",
                "thumbnail": "https://bc.imgix.net/game/image/696df83c-e164-48fd-a596-e6b705ef41b0.png",
                "providerName": "Neko Games",
                "rtpDes": 95.00000000,
                "iconThreeFour": "https://bc.imgix.net/game/image/common.png",
                "betco34": "https://bc.imgix.net/game/image/common.png",
                "online": 3,
                "providerIcon": "https://bc.imgix.net/game/image/32f0dc4f00.png",
                "providerIconWhite": "https://bc.imgix.net/game/image/a499f47477.png",
                "isRestricted": 0,
                "categoryName": "Slots",
                "rateScore": 4,
                "rateNum": 1,
                "retrieveId": "hot",
                "onlineUsers": 1,
                "tags": [
                    "Buy extra ball feature",
                    "Bingo jackpot",
                    "Microgaming",
                    "Ancient",
                    "High volatility",
                    "Bingo"
                ],
                "corner": null,
                "wagerPercentAge": 50.00000000,
                "translatedTags": {},
                "disabled": false
            },
            {
                "gameIdentity": {
                    "gameInfoId": 18362,
                    "gameName": "TADA70:174",
                    "gameUrl": "jackpot-bingo-by-tada",
                    "gameChannel": "0",
                    "socketNameSpace": "jackpot-bingo-by-tada"
                },
                "fullName": "Jackpot Bingo",
                "thumbnail": "https://bc.imgix.net/game/image/197c153328.png",
                "providerName": "TaDa",
                "rtpDes": 97.00000000,
                "iconThreeFour": "https://bc.imgix.net/game/image/5195c22f56.png",
                "betco34": "https://bc.imgix.net/game/image/common.png",
                "online": 3,
                "providerIcon": "https://bc.imgix.net/game/image/aa905d6c31.png",
                "providerIconWhite": "https://bc.imgix.net/game/image/3ad4290103.png",
                "isRestricted": 0,
                "categoryName": "Slots",
                "rateScore": 4,
                "rateNum": 1,
                "retrieveId": "hot",
                "onlineUsers": 1,
                "tags": [
                    "Buy extra ball feature",
                    "Bingo jackpot",
                    "Bingo"
                ],
                "corner": null,
                "wagerPercentAge": 50.00000000,
                "translatedTags": {},
                "disabled": false
            }, {
                "gameIdentity": {
                    "gameInfoId": 18946,
                    "gameName": "CRO12:142",
                    "gameUrl": "wukong-by-bc-originals",
                    "gameChannel": "0",
                    "socketNameSpace": "wukong-by-bc-originals"
                },
                "fullName": "WUKONG",
                "thumbnail": "https://bc.imgix.net/game/image/a3adc0e76f.png",
                "providerName": "BC Originals",
                "rtpDes": 95.98000000,
                "iconThreeFour": "https://bc.imgix.net/game/image/6b0de1a65a.png",
                "betco34": "https://bc.imgix.net/game/image/common.png",
                "online": 3,
                "providerIcon": "https://bc.imgix.net/game/image/f11fb1c8d6.png",
                "providerIconWhite": "https://bc.imgix.net/game/image/0c201cc018.png",
                "isRestricted": 0,
                "categoryName": "Original Casino",
                "rateScore": 4,
                "rateNum": 1,
                "retrieveId": "hot",
                "onlineUsers": 40,
                "tags": [
                    "BC Exclusive",
                    "Chinese myths",
                    "Ruyi bang",
                    "Wukong",
                    "Black myth",
                    "Upgrade challenges",
                    "BC Originals",
                    "Cascading Reels",
                    "Mythology",
                    "Game of the year",
                    "Journey to the west"
                ],
                "corner": "Exclusive",
                "wagerPercentAge": 100.00000000,
                "translatedTags": {},
                "disabled": false
            },
            {
                "gameIdentity": {
                    "gameInfoId": 16353,
                    "gameName": "evo21:roulette:r4dcwwxx47rywy5n",
                    "gameUrl": "evo21-roulette-r4dcwwxx47rywy5n",
                    "gameChannel": "0",
                    "socketNameSpace": "evo21-roulette-r4dcwwxx47rywy5n"
                },
                "fullName": "BCGAME Roulette",
                "thumbnail": "https://bc.imgix.net/game/image/b8727bbd3d.png",
                "providerName": "Evolution Gaming",
                "rtpDes": 98.26000000,
                "iconThreeFour": "https://bc.imgix.net/game/image/576dbdc8dd.png",
                "betco34": "https://bc.imgix.net/game/image/common.png",
                "online": 3,
                "providerIcon": "https://bc.imgix.net/game/image/9c40f44618.png",
                "providerIconWhite": "https://bc.imgix.net/game/image/987c6d21e6.png",
                "isRestricted": 0,
                "categoryName": "Live Casino",
                "rateScore": 4,
                "rateNum": 1,
                "retrieveId": "hot",
                "onlineUsers": 58,
                "tags": [
                    "BC Exclusive"
                ],
                "corner": "Exclusive",
                "wagerPercentAge": null,
                "translatedTags": {},
                "disabled": false
            },
            {
                "gameIdentity": {
                    "gameInfoId": 12498,
                    "gameName": "softswiss:softswiss:BCCash",
                    "gameUrl": "bc-cash-by-bgaming",
                    "gameChannel": "0",
                    "socketNameSpace": "bc-cash-by-bgaming"
                },
                "fullName": "BC Cash",
                "thumbnail": "https://bc.imgix.net/game/image/bd433bfa-c8fa-4d60-a42c-fed1280c4831.png",
                "providerName": "BGaming",
                "rtpDes": 96.00000000,
                "iconThreeFour": "https://bc.imgix.net/game/image/12498_BC Cash.png",
                "betco34": "https://bc.imgix.net/game/image/common.png",
                "online": 3,
                "providerIcon": "https://bc.imgix.net/game/image/75b5d81876.png",
                "providerIconWhite": "https://bc.imgix.net/game/image/2deb73385c.png",
                "isRestricted": 0,
                "categoryName": "Slots",
                "rateScore": 4,
                "rateNum": 1,
                "retrieveId": "hot",
                "onlineUsers": 9,
                "tags": [
                    "BC Exclusive",
                    "Feature buy-in",
                    "High volatility",
                    "Diamonds"
                ],
                "corner": "Exclusive",
                "wagerPercentAge": 100.00000000,
                "translatedTags": {},
                "disabled": false
            },
            {
                "gameIdentity": {
                    "gameInfoId": 13884,
                    "gameName": "evo21:blackjack:reyezjtolwpf37px",
                    "gameUrl": "bc-blackjack-b-by-evolution-gaming",
                    "gameChannel": "0",
                    "socketNameSpace": "bc-blackjack-b-by-evolution-gaming"
                },
                "fullName": "BC Blackjack B",
                "thumbnail": "https://bc.imgix.net/game/image/456448c5-6754-4afc-b542-81aee53bde8a.png",
                "providerName": "Evolution Gaming",
                "rtpDes": 99.00000000,
                "iconThreeFour": "https://bc.imgix.net/game/image/d3c1e68ee3.png",
                "betco34": "https://bc.imgix.net/game/image/common.png",
                "online": 3,
                "providerIcon": "https://bc.imgix.net/game/image/9c40f44618.png",
                "providerIconWhite": "https://bc.imgix.net/game/image/987c6d21e6.png",
                "isRestricted": 0,
                "categoryName": "Live Casino",
                "rateScore": 4,
                "rateNum": 1,
                "retrieveId": "hot",
                "onlineUsers": 6,
                "tags": [
                    "BC Exclusive",
                    "Blackjack",
                    "VIP Blackjack",
                    "Dedicated"
                ],
                "corner": "Exclusive",
                "wagerPercentAge": null,
                "translatedTags": {},
                "disabled": false
            },
            {
                "gameIdentity": {
                    "gameInfoId": 13883,
                    "gameName": "evo21:blackjack:reyd5odmlwpfzjdw",
                    "gameUrl": "bcgame-blackjack-a-by-evolution-gaming",
                    "gameChannel": "0",
                    "socketNameSpace": "bcgame-blackjack-a-by-evolution-gaming"
                },
                "fullName": "BCGAME Blackjack A",
                "thumbnail": "https://bc.imgix.net/game/image/23ab542e-1733-44f4-ba28-51e6d185097c.png",
                "providerName": "Evolution Gaming",
                "rtpDes": 99.00000000,
                "iconThreeFour": "https://bc.imgix.net/game/image/3ff8c83648.png",
                "betco34": "https://bc.imgix.net/game/image/common.png",
                "online": 3,
                "providerIcon": "https://bc.imgix.net/game/image/9c40f44618.png",
                "providerIconWhite": "https://bc.imgix.net/game/image/987c6d21e6.png",
                "isRestricted": 0,
                "categoryName": "Live Casino",
                "rateScore": 4,
                "rateNum": 1,
                "retrieveId": "hot",
                "onlineUsers": 2,
                "tags": [
                    "BC Exclusive",
                    "Blackjack"
                ],
                "corner": "Exclusive",
                "wagerPercentAge": null,
                "translatedTags": {},
                "disabled": false
            },
            {
                "gameIdentity": {
                    "gameInfoId": 16351,
                    "gameName": "evo21:blackjack:r4dccjre47rytlgz",
                    "gameUrl": "bcgame-blackjack-c-by-evolution-gaming",
                    "gameChannel": "0",
                    "socketNameSpace": "bcgame-blackjack-c-by-evolution-gaming"
                },
                "fullName": "BCGAME Blackjack C",
                "thumbnail": "https://bc.imgix.net/game/image/f2e76c6f50.png",
                "providerName": "Evolution Gaming",
                "rtpDes": 99.29000000,
                "iconThreeFour": "https://bc.imgix.net/game/image/33b3286cc1.png",
                "betco34": "https://bc.imgix.net/game/image/common.png",
                "online": 3,
                "providerIcon": "https://bc.imgix.net/game/image/9c40f44618.png",
                "providerIconWhite": "https://bc.imgix.net/game/image/987c6d21e6.png",
                "isRestricted": 0,
                "categoryName": "Live Casino",
                "rateScore": 4,
                "rateNum": 1,
                "retrieveId": "hot",
                "onlineUsers": 3,
                "tags": [
                    "BC Exclusive",
                    "Blackjack"
                ],
                "corner": "Exclusive",
                "wagerPercentAge": null,
                "translatedTags": {},
                "disabled": false
            },
            {
                "gameIdentity": {
                    "gameInfoId": 14077,
                    "gameName": "evo21:blackjack:rgea7vnq54ehg2fs",
                    "gameUrl": "bcgame-speed-blackjack-by-evolution-gaming",
                    "gameChannel": "0",
                    "socketNameSpace": "bcgame-speed-blackjack-by-evolution-gaming"
                },
                "fullName": "BCGAME Speed Blackjack",
                "thumbnail": "https://bc.imgix.net/game/image/97a68437-78ce-482a-9ceb-c566fca84e3f.png",
                "providerName": "Evolution Gaming",
                "rtpDes": 99.00000000,
                "iconThreeFour": "https://bc.imgix.net/game/image/91f86a1e4c.png",
                "betco34": "https://bc.imgix.net/game/image/common.png",
                "online": 3,
                "providerIcon": "https://bc.imgix.net/game/image/9c40f44618.png",
                "providerIconWhite": "https://bc.imgix.net/game/image/987c6d21e6.png",
                "isRestricted": 0,
                "categoryName": "Live Casino",
                "rateScore": 4,
                "rateNum": 1,
                "retrieveId": "hot",
                "onlineUsers": 1,
                "tags": [
                    "BC Exclusive",
                    "Multiplayer",
                    "Multi-Hand blackjack",
                    "Blackjack",
                    "VIP Blackjack",
                    "Dedicated"
                ],
                "corner": "Exclusive",
                "wagerPercentAge": null,
                "translatedTags": {},
                "disabled": false
            },
            {
                "gameIdentity": {
                    "gameInfoId": 8913,
                    "gameName": "softswiss:softswiss:BCBonanza",
                    "gameUrl": "bc-bonanza-by-bgaming",
                    "gameChannel": "0",
                    "socketNameSpace": "bc-bonanza-by-bgaming"
                },
                "fullName": "BC Bonanza",
                "thumbnail": "https://bc.imgix.net/game/image/ca454c31-46f8-4567-8c6f-c138d5f12078.png",
                "providerName": "BGaming",
                "rtpDes": 96.00000000,
                "iconThreeFour": "https://bc.imgix.net/game/image/8913_BC Bonanza.png",
                "betco34": "https://bc.imgix.net/game/image/common.png",
                "online": 3,
                "providerIcon": "https://bc.imgix.net/game/image/75b5d81876.png",
                "providerIconWhite": "https://bc.imgix.net/game/image/2deb73385c.png",
                "isRestricted": 0,
                "categoryName": "Slots",
                "rateScore": 4,
                "rateNum": 1,
                "retrieveId": "hot",
                "onlineUsers": 1,
                "tags": [
                    "BC Exclusive",
                    "Scatter symbols",
                    "Feature buy-in",
                    "Cascading Reels",
                    "High volatility",
                    "Fruits"
                ],
                "corner": "Exclusive",
                "wagerPercentAge": 100.00000000,
                "translatedTags": {},
                "disabled": false
            },
            {
                "gameIdentity": {
                    "gameInfoId": 5834,
                    "gameName": "softswiss:softswiss:BCMillion",
                    "gameUrl": "bc-million-by-bgaming",
                    "gameChannel": "0",
                    "socketNameSpace": "bc-million-by-bgaming"
                },
                "fullName": "BC.Million",
                "thumbnail": "https://bc.imgix.net/game/image/99882557-0636-49b3-8695-ec2b38f75842.png",
                "providerName": "BGaming",
                "rtpDes": 97.10000000,
                "iconThreeFour": "https://bc.imgix.net/game/image/5834_BC.Million.png",
                "betco34": "https://bc.imgix.net/game/image/common.png",
                "online": 3,
                "providerIcon": "https://bc.imgix.net/game/image/75b5d81876.png",
                "providerIconWhite": "https://bc.imgix.net/game/image/2deb73385c.png",
                "isRestricted": 0,
                "categoryName": "Slots",
                "rateScore": 4,
                "rateNum": 1,
                "retrieveId": "hot",
                "onlineUsers": 1,
                "tags": [
                    "BC Exclusive",
                    "Scatter symbols",
                    "Gamble feature",
                    "High volatility",
                    "Expanding Symbols",
                    "Fruits"
                ],
                "corner": "Exclusive",
                "wagerPercentAge": 50.00000000,
                "translatedTags": {},
                "disabled": false
            },
            {
                "gameIdentity": {
                    "gameInfoId": 14078,
                    "gameName": "evo21:blackjack:rgdzue7v4xaga5s5",
                    "gameUrl": "evo21-blackjack-rgdzue7v4xaga5s5",
                    "gameChannel": "0",
                    "socketNameSpace": "evo21-blackjack-rgdzue7v4xaga5s5"
                },
                "fullName": "BCGAME VIP Blackjack",
                "thumbnail": "https://bc.imgix.net/game/image/b3656cf3-a6e7-4de0-9159-77e9a0e7a21c.png",
                "providerName": "Evolution Gaming",
                "rtpDes": 99.00000000,
                "iconThreeFour": "https://bc.imgix.net/game/image/34ea0dae26.png",
                "betco34": "https://bc.imgix.net/game/image/common.png",
                "online": 3,
                "providerIcon": "https://bc.imgix.net/game/image/9c40f44618.png",
                "providerIconWhite": "https://bc.imgix.net/game/image/987c6d21e6.png",
                "isRestricted": 0,
                "categoryName": "Live Casino",
                "rateScore": 4,
                "rateNum": 1,
                "retrieveId": "hot",
                "onlineUsers": 2,
                "tags": [
                    "BC Exclusive",
                    "Multiplayer",
                    "Multi-Hand blackjack",
                    "Blackjack",
                    "VIP Blackjack",
                    "Dedicated"
                ],
                "corner": "Exclusive",
                "wagerPercentAge": null,
                "translatedTags": {},
                "disabled": false
            }, {
                "gameIdentity": {
                    "gameInfoId": 20806,
                    "gameName": "FCG46:21006",
                    "gameUrl": "fierce-fishing-by-fa-chai",
                    "gameChannel": "0",
                    "socketNameSpace": "fierce-fishing-by-fa-chai"
                },
                "fullName": "FIERCE FISHING",
                "thumbnail": "https://bc.imgix.net/game/image/d5ad337ac8.png",
                "providerName": "FA CHAI",
                "rtpDes": 97.00000000,
                "iconThreeFour": "https://bc.imgix.net/game/image/ea0a79ff0a.png",
                "betco34": "https://bc.imgix.net/game/image/common.png",
                "online": 3,
                "providerIcon": "https://bc.imgix.net/game/image/b6fa55fc56.png",
                "providerIconWhite": "https://bc.imgix.net/game/image/c9a000ca3e.png",
                "isRestricted": 0,
                "categoryName": "Slots",
                "rateScore": 4,
                "rateNum": 1,
                "retrieveId": "hot",
                "onlineUsers": 2,
                "tags": [
                    "Fishing"
                ],
                "corner": null,
                "wagerPercentAge": null,
                "translatedTags": {},
                "disabled": false
            },
            {
                "gameIdentity": {
                    "gameInfoId": 20804,
                    "gameName": "FCG46:21003",
                    "gameUrl": "monkey-king-fishing-by-fa-chai",
                    "gameChannel": "0",
                    "socketNameSpace": "monkey-king-fishing-by-fa-chai"
                },
                "fullName": "MONKEY KING FISHING",
                "thumbnail": "https://bc.imgix.net/game/image/1884d1a743.png",
                "providerName": "FA CHAI",
                "rtpDes": 97.00000000,
                "iconThreeFour": "https://bc.imgix.net/game/image/047a90f9a9.png",
                "betco34": "https://bc.imgix.net/game/image/common.png",
                "online": 3,
                "providerIcon": "https://bc.imgix.net/game/image/b6fa55fc56.png",
                "providerIconWhite": "https://bc.imgix.net/game/image/c9a000ca3e.png",
                "isRestricted": 0,
                "categoryName": "Slots",
                "rateScore": 4,
                "rateNum": 1,
                "retrieveId": "hot",
                "onlineUsers": 1,
                "tags": [
                    "Fishing"
                ],
                "corner": null,
                "wagerPercentAge": null,
                "translatedTags": {},
                "disabled": false
            },
            {
                "gameIdentity": {
                    "gameInfoId": 20802,
                    "gameName": "FCG46:21008",
                    "gameUrl": "star-hunter-by-fa-chai",
                    "gameChannel": "0",
                    "socketNameSpace": "star-hunter-by-fa-chai"
                },
                "fullName": "STAR HUNTER",
                "thumbnail": "https://bc.imgix.net/game/image/f905b7c3fe.png",
                "providerName": "FA CHAI",
                "rtpDes": 97.00000000,
                "iconThreeFour": "https://bc.imgix.net/game/image/40acec2c83.png",
                "betco34": "https://bc.imgix.net/game/image/common.png",
                "online": 3,
                "providerIcon": "https://bc.imgix.net/game/image/b6fa55fc56.png",
                "providerIconWhite": "https://bc.imgix.net/game/image/c9a000ca3e.png",
                "isRestricted": 0,
                "categoryName": "Slots",
                "rateScore": 4,
                "rateNum": 1,
                "retrieveId": "hot",
                "onlineUsers": 1,
                "tags": [
                    "Fishing"
                ],
                "corner": null,
                "wagerPercentAge": null,
                "translatedTags": {},
                "disabled": false
            },
            {
                "gameIdentity": {
                    "gameInfoId": 20803,
                    "gameName": "FCG46:21009",
                    "gameUrl": "gods-grant-fortune-by-fa-chai",
                    "gameChannel": "0",
                    "socketNameSpace": "gods-grant-fortune-by-fa-chai"
                },
                "fullName": "GODS GRANT FORTUNE",
                "thumbnail": "https://bc.imgix.net/game/image/33adc7b98d.png",
                "providerName": "FA CHAI",
                "rtpDes": 97.00000000,
                "iconThreeFour": "https://bc.imgix.net/game/image/d708ca1e57.png",
                "betco34": "https://bc.imgix.net/game/image/common.png",
                "online": 3,
                "providerIcon": "https://bc.imgix.net/game/image/b6fa55fc56.png",
                "providerIconWhite": "https://bc.imgix.net/game/image/c9a000ca3e.png",
                "isRestricted": 0,
                "categoryName": "Slots",
                "rateScore": 4,
                "rateNum": 1,
                "retrieveId": "hot",
                "onlineUsers": 2,
                "tags": [
                    "Fishing"
                ],
                "corner": null,
                "wagerPercentAge": null,
                "translatedTags": {},
                "disabled": false
            },
            {
                "gameIdentity": {
                    "gameInfoId": 20805,
                    "gameName": "FCG46:21004",
                    "gameUrl": "bao-chuan-fishing-by-fa-chai",
                    "gameChannel": "0",
                    "socketNameSpace": "bao-chuan-fishing-by-fa-chai"
                },
                "fullName": "BAO CHUAN FISHING",
                "thumbnail": "https://bc.imgix.net/game/image/b31a24ed9a.png",
                "providerName": "FA CHAI",
                "rtpDes": 97.00000000,
                "iconThreeFour": "https://bc.imgix.net/game/image/ad1aba24ec.png",
                "betco34": "https://bc.imgix.net/game/image/common.png",
                "online": 3,
                "providerIcon": "https://bc.imgix.net/game/image/b6fa55fc56.png",
                "providerIconWhite": "https://bc.imgix.net/game/image/c9a000ca3e.png",
                "isRestricted": 0,
                "categoryName": "Slots",
                "rateScore": 4,
                "rateNum": 1,
                "retrieveId": "hot",
                "onlineUsers": 2,
                "tags": [
                    "Fishing"
                ],
                "corner": null,
                "wagerPercentAge": null,
                "translatedTags": {},
                "disabled": false
            },
            {
                "gameIdentity": {
                    "gameInfoId": 20807,
                    "gameName": "spg20:F-FL01",
                    "gameUrl": "fishing-legend-by-spadegaming",
                    "gameChannel": "0",
                    "socketNameSpace": "fishing-legend-by-spadegaming"
                },
                "fullName": "Fishing Legend",
                "thumbnail": "https://bc.imgix.net/game/image/3e34e12a9d.png",
                "providerName": "Spadegaming",
                "rtpDes": 96.50000000,
                "iconThreeFour": "https://bc.imgix.net/game/image/68dcf41478.png",
                "betco34": "https://bc.imgix.net/game/image/common.png",
                "online": 3,
                "providerIcon": "https://bc.imgix.net/game/image/408156443a.png",
                "providerIconWhite": "https://bc.imgix.net/game/image/67a355300d.png",
                "isRestricted": 0,
                "categoryName": "Slots",
                "rateScore": 4,
                "rateNum": 1,
                "retrieveId": "hot",
                "onlineUsers": 2,
                "tags": [
                    "Fishing"
                ],
                "corner": null,
                "wagerPercentAge": null,
                "translatedTags": {},
                "disabled": false
            },
            {
                "gameIdentity": {
                    "gameInfoId": 9749,
                    "gameName": "spg20:F-ZP01",
                    "gameUrl": "zombie-party-by-spadegaming",
                    "gameChannel": "0",
                    "socketNameSpace": "zombie-party-by-spadegaming"
                },
                "fullName": "Zombie Party",
                "thumbnail": "https://bc.imgix.net/game/image/91a2581204.png",
                "providerName": "Spadegaming",
                "rtpDes": 97.00000000,
                "iconThreeFour": "https://bc.imgix.net/game/image/bfc830a7f0.png",
                "betco34": "https://bc.imgix.net/game/image/common.png",
                "online": 3,
                "providerIcon": "https://bc.imgix.net/game/image/408156443a.png",
                "providerIconWhite": "https://bc.imgix.net/game/image/67a355300d.png",
                "isRestricted": 0,
                "categoryName": "Slots",
                "rateScore": 4,
                "rateNum": 1,
                "retrieveId": "hot",
                "onlineUsers": 1,
                "tags": [
                    "Fishing"
                ],
                "corner": null,
                "wagerPercentAge": null,
                "translatedTags": {},
                "disabled": false
            },
            {
                "gameIdentity": {
                    "gameInfoId": 9751,
                    "gameName": "spg20:F-SF01",
                    "gameUrl": "fishing-god-by-spadegaming",
                    "gameChannel": "0",
                    "socketNameSpace": "fishing-god-by-spadegaming"
                },
                "fullName": "Fishing God",
                "thumbnail": "https://bc.imgix.net/game/image/44cb1a008b.png",
                "providerName": "Spadegaming",
                "rtpDes": 97.00000000,
                "iconThreeFour": "https://bc.imgix.net/game/image/1cc1d10ee2.png",
                "betco34": "https://bc.imgix.net/game/image/common.png",
                "online": 3,
                "providerIcon": "https://bc.imgix.net/game/image/408156443a.png",
                "providerIconWhite": "https://bc.imgix.net/game/image/67a355300d.png",
                "isRestricted": 0,
                "categoryName": "Slots",
                "rateScore": 4,
                "rateNum": 1,
                "retrieveId": "hot",
                "onlineUsers": 1,
                "tags": [
                    "Fishing"
                ],
                "corner": null,
                "wagerPercentAge": null,
                "translatedTags": {},
                "disabled": false
            },
            {
                "gameIdentity": {
                    "gameInfoId": 20809,
                    "gameName": "TOP45:068",
                    "gameUrl": "fortune-fishing-by-ygr",
                    "gameChannel": "0",
                    "socketNameSpace": "fortune-fishing-by-ygr"
                },
                "fullName": "Fortune Fishing",
                "thumbnail": "https://bc.imgix.net/game/image/7176c110b8.png",
                "providerName": "YGR",
                "rtpDes": 97.00000000,
                "iconThreeFour": "https://bc.imgix.net/game/image/c43015ebc1.png",
                "betco34": "https://bc.imgix.net/game/image/common.png",
                "online": 3,
                "providerIcon": "https://bc.imgix.net/game/image/57ac747754.png",
                "providerIconWhite": "https://bc.imgix.net/game/image/3ad63c4823.png",
                "isRestricted": 0,
                "categoryName": "Slots",
                "rateScore": 4,
                "rateNum": 1,
                "retrieveId": "hot",
                "onlineUsers": 2,
                "tags": [
                    "Fishing"
                ],
                "corner": null,
                "wagerPercentAge": null,
                "translatedTags": {},
                "disabled": false
            },
            {
                "gameIdentity": {
                    "gameInfoId": 14131,
                    "gameName": "TOP45:030",
                    "gameUrl": "chill-fishing-by-ygr",
                    "gameChannel": "0",
                    "socketNameSpace": "chill-fishing-by-ygr"
                },
                "fullName": "Chill Fishing",
                "thumbnail": "https://bc.imgix.net/game/image/d066a6974b.png",
                "providerName": "YGR",
                "rtpDes": 95.00000000,
                "iconThreeFour": "https://bc.imgix.net/game/image/854919d5ac.png",
                "betco34": "https://bc.imgix.net/game/image/common.png",
                "online": 3,
                "providerIcon": "https://bc.imgix.net/game/image/57ac747754.png",
                "providerIconWhite": "https://bc.imgix.net/game/image/3ad63c4823.png",
                "isRestricted": 0,
                "categoryName": "Slots",
                "rateScore": 4,
                "rateNum": 1,
                "retrieveId": "hot",
                "onlineUsers": 1,
                "tags": [
                    "Fishing"
                ],
                "corner": null,
                "wagerPercentAge": null,
                "translatedTags": {},
                "disabled": false
            }, {
                "gameIdentity": {
                    "gameInfoId": 1020,
                    "gameName": "roulette",
                    "gameUrl": "roulette-multiplayer",
                    "gameChannel": "1",
                    "socketNameSpace": "/g/rl"
                },
                "fullName": "Roulette Multiplayer",
                "thumbnail": "https://bc.imgix.net/game/image/40cf4d7a-73f0-4c66-bffb-370e4f6286f7.png",
                "providerName": "BC Originals",
                "rtpDes": 96.00000000,
                "iconThreeFour": "https://bc.imgix.net/game/image/c868874e85.png",
                "betco34": "https://bc.imgix.net/game/image/common.png",
                "online": 3,
                "providerIcon": "https://bc.imgix.net/game/image/f11fb1c8d6.png",
                "providerIconWhite": "https://bc.imgix.net/game/image/0c201cc018.png",
                "isRestricted": 0,
                "categoryName": "Original Casino",
                "rateScore": 4,
                "rateNum": 1,
                "retrieveId": "hot",
                "onlineUsers": 32,
                "tags": [
                    "Multiplayer",
                    "BC Originals",
                    "Table games",
                    "Roulette",
                    "Provably fair"
                ],
                "corner": null,
                "wagerPercentAge": 5.00000000,
                "translatedTags": {},
                "disabled": false
            },
            {
                "gameIdentity": {
                    "gameInfoId": 1019,
                    "gameName": "blackjack",
                    "gameUrl": "blackjack",
                    "gameChannel": "1",
                    "socketNameSpace": "/g/bj"
                },
                "fullName": "Blackjack",
                "thumbnail": "https://bc.imgix.net/game/image/3a5b3697-a9ac-4492-a223-6e404ecdb3d3.png",
                "providerName": "BC Originals",
                "rtpDes": 99.52000000,
                "iconThreeFour": "https://bc.imgix.net/game/image/21b3ecd3c3.png",
                "betco34": "https://bc.imgix.net/game/image/common.png",
                "online": 1,
                "providerIcon": "https://bc.imgix.net/game/image/f11fb1c8d6.png",
                "providerIconWhite": "https://bc.imgix.net/game/image/0c201cc018.png",
                "isRestricted": 0,
                "categoryName": "Original Casino",
                "rateScore": 4,
                "rateNum": 1,
                "retrieveId": "hot",
                "onlineUsers": 5,
                "tags": [
                    "BC Originals",
                    "Table games",
                    "Blackjack",
                    "Provably fair"
                ],
                "corner": null,
                "wagerPercentAge": 5.00000000,
                "translatedTags": {},
                "disabled": false
            },
            {
                "gameIdentity": {
                    "gameInfoId": 5277,
                    "gameName": "evo21:rng-blackjack:rng-bj-standard0",
                    "gameUrl": "first-person-blackjack-by-evolution-gaming",
                    "gameChannel": "0",
                    "socketNameSpace": "first-person-blackjack-by-evolution-gaming"
                },
                "fullName": "First Person Blackjack",
                "thumbnail": "https://bc.imgix.net/game/image/61ec76e5-7dec-49dd-9511-7880ff2bcd5a.png",
                "providerName": "Evolution Gaming",
                "rtpDes": 99.00000000,
                "iconThreeFour": "https://bc.imgix.net/game/image/5277_First Person Blackjack.png",
                "betco34": "https://bc.imgix.net/game/image/common.png",
                "online": 3,
                "providerIcon": "https://bc.imgix.net/game/image/9c40f44618.png",
                "providerIconWhite": "https://bc.imgix.net/game/image/987c6d21e6.png",
                "isRestricted": 0,
                "categoryName": "Slots",
                "rateScore": 4,
                "rateNum": 1,
                "retrieveId": "hot",
                "onlineUsers": 2,
                "tags": [
                    "Table games"
                ],
                "corner": null,
                "wagerPercentAge": null,
                "translatedTags": {},
                "disabled": false
            },
            {
                "gameIdentity": {
                    "gameInfoId": 15252,
                    "gameName": "BaccaratSingle96",
                    "gameUrl": "baccarat",
                    "gameChannel": "1",
                    "socketNameSpace": "/g/baccarat-single/96"
                },
                "fullName": "Baccarat",
                "thumbnail": "https://bc.imgix.net/game/image/3911eb66-be55-4674-8d2b-221d6cdaac6d.png",
                "providerName": "BC Originals",
                "rtpDes": 96.00000000,
                "iconThreeFour": "https://bc.imgix.net/game/image/276b713992.png",
                "betco34": "https://bc.imgix.net/game/image/common.png",
                "online": 1,
                "providerIcon": "https://bc.imgix.net/game/image/f11fb1c8d6.png",
                "providerIconWhite": "https://bc.imgix.net/game/image/0c201cc018.png",
                "isRestricted": 0,
                "categoryName": "Original Casino",
                "rateScore": 4,
                "rateNum": 1,
                "retrieveId": "hot",
                "onlineUsers": 3,
                "tags": [
                    "BC Originals",
                    "Table games",
                    "Baccarat",
                    "Provably fair"
                ],
                "corner": null,
                "wagerPercentAge": 5.00000000,
                "translatedTags": {},
                "disabled": false
            },
            {
                "gameIdentity": {
                    "gameInfoId": 1010,
                    "gameName": "Baccarat",
                    "gameUrl": "baccarat-multiplayer",
                    "gameChannel": "1",
                    "socketNameSpace": "/g/bacc/main"
                },
                "fullName": "Baccarat Multiplayer",
                "thumbnail": "https://bc.imgix.net/game/image/64f91955-6dd2-4f7e-a75b-ed5a11222886.png",
                "providerName": "BC Originals",
                "rtpDes": 99.00000000,
                "iconThreeFour": "https://bc.imgix.net/game/image/5234690cec.png",
                "betco34": "https://bc.imgix.net/game/image/common.png",
                "online": 3,
                "providerIcon": "https://bc.imgix.net/game/image/f11fb1c8d6.png",
                "providerIconWhite": "https://bc.imgix.net/game/image/0c201cc018.png",
                "isRestricted": 0,
                "categoryName": "Original Casino",
                "rateScore": 4,
                "rateNum": 1,
                "retrieveId": "hot",
                "onlineUsers": 1,
                "tags": [
                    "BC Originals",
                    "Table games",
                    "Baccarat",
                    "Provably fair"
                ],
                "corner": null,
                "wagerPercentAge": 5.00000000,
                "translatedTags": {},
                "disabled": false
            },
            {
                "gameIdentity": {
                    "gameInfoId": 5354,
                    "gameName": "evo21:rng-roulette:rng-rt-european0",
                    "gameUrl": "first-person-roulette-by-evolution-gaming",
                    "gameChannel": "0",
                    "socketNameSpace": "first-person-roulette-by-evolution-gaming"
                },
                "fullName": "First Person Roulette",
                "thumbnail": "https://bc.imgix.net/game/image/69a200e0-f219-44d6-85d1-f4e6819c1f86.png",
                "providerName": "Evolution Gaming",
                "rtpDes": 97.00000000,
                "iconThreeFour": "https://bc.imgix.net/game/image/5354_First Person Roulette.png",
                "betco34": "https://bc.imgix.net/game/image/common.png",
                "online": 3,
                "providerIcon": "https://bc.imgix.net/game/image/9c40f44618.png",
                "providerIconWhite": "https://bc.imgix.net/game/image/987c6d21e6.png",
                "isRestricted": 0,
                "categoryName": "Live Casino",
                "rateScore": 4,
                "rateNum": 1,
                "retrieveId": "hot",
                "onlineUsers": 3,
                "tags": [
                    "Table games"
                ],
                "corner": null,
                "wagerPercentAge": null,
                "translatedTags": {},
                "disabled": false
            },
            {
                "gameIdentity": {
                    "gameInfoId": 11529,
                    "gameName": "evo21:rng-dealnodeal:RngDealNoDeal001",
                    "gameUrl": "first-person-deal-or-no-deal-by-evolution-gaming",
                    "gameChannel": "0",
                    "socketNameSpace": "first-person-deal-or-no-deal-by-evolution-gaming"
                },
                "fullName": "First Person Deal or No Deal",
                "thumbnail": "https://bc.imgix.net/game/image/dfbb442c-ed05-4722-9494-90b04d3878ab.png",
                "providerName": "Evolution Gaming",
                "rtpDes": 95.00000000,
                "iconThreeFour": "https://bc.imgix.net/game/image/11529_First Person Deal or No Deal.png",
                "betco34": "https://bc.imgix.net/game/image/common.png",
                "online": 3,
                "providerIcon": "https://bc.imgix.net/game/image/9c40f44618.png",
                "providerIconWhite": "https://bc.imgix.net/game/image/987c6d21e6.png",
                "isRestricted": 0,
                "categoryName": "Slots",
                "rateScore": 4,
                "rateNum": 1,
                "retrieveId": "hot",
                "onlineUsers": 1,
                "tags": [
                    "Bet behind",
                    "Table games",
                    "Live Casino"
                ],
                "corner": null,
                "wagerPercentAge": 5.00000000,
                "translatedTags": {},
                "disabled": false
            },
            {
                "gameIdentity": {
                    "gameInfoId": 5349,
                    "gameName": "evo21:rng-megaball:RngMegaBall00001",
                    "gameUrl": "first-person-mega-ball-by-evolution-gaming",
                    "gameChannel": "0",
                    "socketNameSpace": "first-person-mega-ball-by-evolution-gaming"
                },
                "fullName": "First Person Mega Ball",
                "thumbnail": "https://bc.imgix.net/game/image/932348db-81d0-45db-8ebb-df2ae08f6de0.png",
                "providerName": "Evolution Gaming",
                "rtpDes": 99.00000000,
                "iconThreeFour": "https://bc.imgix.net/game/image/5349_First Person Mega Ball.png",
                "betco34": "https://bc.imgix.net/game/image/common.png",
                "online": 3,
                "providerIcon": "https://bc.imgix.net/game/image/9c40f44618.png",
                "providerIconWhite": "https://bc.imgix.net/game/image/987c6d21e6.png",
                "isRestricted": 0,
                "categoryName": "Slots",
                "rateScore": 4,
                "rateNum": 1,
                "retrieveId": "hot",
                "onlineUsers": 1,
                "tags": [
                    "Table games",
                    "Game shows",
                    "Bonus wheel",
                    "Recommended Games"
                ],
                "corner": null,
                "wagerPercentAge": null,
                "translatedTags": {},
                "disabled": false
            },
            {
                "gameIdentity": {
                    "gameInfoId": 5334,
                    "gameName": "evo21:rng-moneywheel:rng-dreamcatcher",
                    "gameUrl": "first-person-dream-catcher-by-evolution-gaming",
                    "gameChannel": "0",
                    "socketNameSpace": "first-person-dream-catcher-by-evolution-gaming"
                },
                "fullName": "First Person Dream Catcher",
                "thumbnail": "https://bc.imgix.net/game/image/e3f8a51e-9ca1-4afc-ace2-63147d32aef9.png",
                "providerName": "Evolution Gaming",
                "rtpDes": 99.00000000,
                "iconThreeFour": "https://bc.imgix.net/game/image/5334_First Person Dream Catcher.png",
                "betco34": "https://bc.imgix.net/game/image/common.png",
                "online": 3,
                "providerIcon": "https://bc.imgix.net/game/image/9c40f44618.png",
                "providerIconWhite": "https://bc.imgix.net/game/image/987c6d21e6.png",
                "isRestricted": 0,
                "categoryName": "Slots",
                "rateScore": 4,
                "rateNum": 1,
                "retrieveId": "hot",
                "onlineUsers": 1,
                "tags": [
                    "Table games"
                ],
                "corner": null,
                "wagerPercentAge": null,
                "translatedTags": {},
                "disabled": false
            },
            {
                "gameIdentity": {
                    "gameInfoId": 2851,
                    "gameName": "PPS32:blackjack",
                    "gameUrl": "blackjack-by-platipus",
                    "gameChannel": "0",
                    "socketNameSpace": "blackjack-by-platipus"
                },
                "fullName": "Blackjack",
                "thumbnail": "https://bc.imgix.net/game/image/e53cbab4-d55b-4cf1-852d-d0e79eb48dd5.png",
                "providerName": "Platipus",
                "rtpDes": 97.00000000,
                "iconThreeFour": "https://bc.imgix.net/game/image/2851_Blackjack.png",
                "betco34": "https://bc.imgix.net/game/image/common.png",
                "online": 3,
                "providerIcon": "https://bc.imgix.net/game/image/9aec8f2b38.png",
                "providerIconWhite": "https://bc.imgix.net/game/image/9419418148.png",
                "isRestricted": 0,
                "categoryName": "Slots",
                "rateScore": 4,
                "rateNum": 1,
                "retrieveId": "hot",
                "onlineUsers": 1,
                "tags": [
                    "Table games",
                    "platipus",
                    "Blackjack",
                    "Side bets"
                ],
                "corner": null,
                "wagerPercentAge": 50.00000000,
                "translatedTags": {},
                "disabled": false
            }
        ],
        error: false
    },
    reducers: {
    },
    extraReducers: (builder) => {
        builder.addCase(fetchPosts.fulfilled, (state, action) => {
            state.games = action.payload.data
        });
    }
});

export default storeSlice.reducer;